import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, useLocation } from "react-router-dom";
import { ShoppingCartIcon } from "@heroicons/react/24/outline";
import { useCart } from "../contexts/CartContext";
export const Layout = ({ children }) => {
    const location = useLocation();
    const { getCartCount } = useCart();
    const cartCount = getCartCount();
    const isActive = (path) => {
        return location.pathname === path;
    };
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsxs("nav", { className: "bg-white shadow-sm border-b border-gray-200", children: [_jsx("div", { className: "max-w-6xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex justify-between items-center h-16", children: [_jsx("div", { className: "flex-shrink-0", children: _jsx(Link, { to: "/", className: "text-2xl font-bold text-gray-900", children: "Kuliner" }) }), _jsx("div", { className: "hidden md:block", children: _jsxs("div", { className: "ml-10 flex items-baseline space-x-4", children: [_jsx(Link, { to: "/", className: `px-3 py-2 rounded-md text-sm font-medium transition-colors ${isActive("/") ? "text-yellow-600 bg-yellow-50" : "text-gray-500 hover:text-gray-700"}`, children: "Home" }), _jsx(Link, { to: "/foods", className: `px-3 py-2 rounded-md text-sm font-medium transition-colors ${isActive("/foods") ? "text-yellow-600 bg-yellow-50" : "text-gray-500 hover:text-gray-700"}`, children: "Foods" })] }) }), _jsx("div", { className: "flex items-center", children: _jsxs(Link, { to: "/cart", className: "relative p-2 text-gray-500 hover:text-gray-700 transition-colors", children: [_jsx(ShoppingCartIcon, { className: "h-6 w-6" }), cartCount > 0 && _jsx("span", { className: "absolute -top-1 -right-1 bg-yellow-500 text-white text-xs rounded-full h-5 w-5 flex items-center justify-center font-medium", children: cartCount })] }) })] }) }), _jsx("div", { className: "md:hidden", children: _jsxs("div", { className: "px-2 pt-2 pb-3 space-y-1 sm:px-3 border-t border-gray-200", children: [_jsx(Link, { to: "/", className: `block px-3 py-2 rounded-md text-base font-medium transition-colors ${isActive("/") ? "text-yellow-600 bg-yellow-50" : "text-gray-500 hover:text-gray-700"}`, children: "Home" }), _jsx(Link, { to: "/foods", className: `block px-3 py-2 rounded-md text-base font-medium transition-colors ${isActive("/foods") ? "text-yellow-600 bg-yellow-50" : "text-gray-500 hover:text-gray-700"}`, children: "Foods" })] }) })] }), _jsx("main", { className: "min-h-screen", children: children }), _jsx("footer", { className: "bg-white border-t border-gray-200", children: _jsx("div", { className: "max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-4", children: _jsx("div", { className: "text-center text-sm text-gray-500", children: "2025 Satriyo Rizkyansah" }) }) })] }));
};
